### ISSUE TITLE
Connection Issues with Glove

### ISSUE THREAD

**Issue by SomeshDaga** [Adjuvo/SenseGlove-Unity#19]
Attempting to run the diagnostics scene gives a continuous log of errors to the effect:

`M: Failed to connect to \\.\/dev/ttyACM0`

I have a feeling that the error is due to the prefixed `\\.\` in the device path. The result is that the sdk does not connect to the gloves.

Platforms

- Ubuntu 18.04
- Unity 18.4 (LTS)
- SenseGlove Unity SDK v1.2 (also tried v1.1)

**Comment by MaxLammers** [comment]
Dear SomeshDaga, the SenseGlove Unity Plugin is not (yet) compatible with Linux. Version 1.3 will be compatible through a new SenseGlove API. If you wish to get started on development in Ubuntu right away; I suggest you check it out at  https://github.com/Adjuvo/SenseGlove-API
