### ISSUE TITLE
COM XX: not valid device

### ISSUE THREAD

**Issue by Deepak-Raj-05** [Adjuvo/SenseGlove-Unity#20]
Hello,
I Used sense glove unity plugin 1.2.
My sense glove is not recognized. It shows the message 'COM XX: not valid device'
But when I use plugin 1.1 and 1.0, they work fine.
I tried with unity 2020,2019,2018 and 2017 also. No changes.
Thank you in advance.

**Comment by MaxLammers** [comment]
Diagnosed with Deepak over email and found the bug, which was related to the connection time of Bluetooth serial devices causing wired devices to time out.

Confirmed to be fixed in [this commit](https://github.com/Adjuvo/SenseGlove-Unity/commit/ab12c710ae0d8b713b01af9e8825d0237b1fda77).
