### ISSUE TITLE
Missing drill script?

### ISSUE THREAD

**Issue by olemid** [Adjuvo/SenseGlove-Unity#28]
Hi. When looking at the demo scenes, scene 06_Tool has a drill in it with a script that's missing. I downloaded version 2.4.1 yesterday and had this problem, I haven't looked at older versions yet. Is there something I'm missing or is it a mistake?

**Comment by MaxLammers** [comment]
Hi olemid,

There is indeed a missing script in that example, which I'll be sure to add in the next update (I'm pushing that with some other bugfixes soon). If you need it a.s.a.p.: The script is a part of our [Learning Exercises](https://senseglove.gitlab.io/SenseGloveDocs/unity/tutorial-tasks.html#task-3-create-a-simple-power-tool) page, from which you can grab it too.

**Comment by olemid** [comment]
Great, thank you. It's not something I need, I was just looking through the examples. Appreciate the help!
