### ISSUE TITLE
Can you give more tutorial about dk1

### ISSUE THREAD

**Issue by wwfmnb** [Adjuvo/SenseGlove-Unity#39]
I'm a newbie, I haven't been exposed to this related content, can you give me more instructional videos or articles?

**Comment by MaxLammers** [comment]
Hello there,

With 'dk1', do you mean the [SenseGlove DK1](https://senseglove.gitlab.io/SenseGloveDocs/dk1-glove.html) exoskeleton glove, or the [Nova 1.0](https://senseglove.gitlab.io/SenseGloveDocs/nova-glove.html)?

Either way, we suggest you take a look at [our documentation website for the Unity Plugin](https://senseglove.gitlab.io/SenseGloveDocs/unity/overview.html). If you have further questions, please be more specific on what you require help with.

**Comment by wwfmnb** [comment]
dk1 has some videos you can share with me. I've read your website but I'm still confused https://www.youtube.com/watch?v=1xcv_Zg-VG8 Can you share some demos with me so that it helps me learn (I've seen the examples in the document)
