### ISSUE TITLE
Fingers don't move.

### ISSUE THREAD

**Issue by I501088** [Adjuvo/SenseGlove-Unity#7]
Unity Version: Unity 2017.1.0p5
Everything (FFB, Test scenes, Vibration) working very good and the thumbs moving properly, but the other fingers on both hands don't move at all.

**Comment by MaxLammers** [comment]
Seemed to be an issue with a DK1 prototype using an older version of the SDK (v_0.19). 
Pushing a new version compatible with the DK1's today.
