### ISSUE TITLE
Missing prefab Issue in v0_20 Example scenes

### ISSUE THREAD

**Issue by Ketoma** [Adjuvo/SenseGlove-Unity#8]
Downloaded the v0_20 and while opening the example scenes, I have this missing prefab issue.

![image](https://user-images.githubusercontent.com/5929331/47712791-f74b8100-dc38-11e8-8054-7deed6ecdd07.png)

**Comment by MaxLammers** [comment]
Which version of Unity are you running, Ketoma?

The Sense Glove SDK has been set up using Unity 2018.2.4f1. There is an issue we have run into ourselves where importing packages from Unity 2018 into an older version of Unity (2017 and lower) causes the loss of prefab connections.

**Comment by Ketoma** [comment]
right, thanks Max,
I used 2017.4.5f1 before, now i opened it with 2018.2.10f1 and the prefab issue is resolved.
